### ISSUE TITLE
Compatibility with gleam_stdlib >= 0.48.0

### ISSUE THREAD

**Issue by gertvv** [BrendoCosta/gleb128#2]
bytes_builder was removed in favor of bytes_tree - gleb128 needs to be updated to be compatible.

**Comment by BrendoCosta** [comment]
Hi @gertvv, thanks for reporting!
It seems this change [took place in gleam_stdlib version 0.42.0](https://github.com/gleam-lang/stdlib/blob/main/CHANGELOG.md#v0420---2024-11-15). I updated the package and now it should be able to compile with ```gleam_stdlib >= 0.42.0```. Since the gleam_stdlib is not yet stable, I also scheduled the current action to run on a daily basis, so it will notify me if any more breaking changes like this occur in the stdlib.

**Comment by gertvv** [comment]
Thanks, that's really helped me out. I was now able to upgrade to the latest stdlib in my project. :+1:
